/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiantes;

import javax.swing.JOptionPane;

/**
 *
 * @author Juana Isabel
 */
public class EstudianteMDIAplication extends javax.swing.JFrame {

    /**
     * Creates new form EstudianteMDIAplication
     */
    public EstudianteMDIAplication() {
        initComponents();
        setTitle("MDI Estudiante");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnEstudiante = new javax.swing.JButton();
        btnAcercaDe1 = new javax.swing.JButton();
        btnEstudiante1 = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu2 = new javax.swing.JMenu();
        exitMenuItem2 = new javax.swing.JMenuItem();
        JMenuAcerca = new javax.swing.JMenu();
        menuItemInformacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(EstudianteMDIAplication.MAXIMIZED_BOTH);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btnEstudiante.setContentAreaFilled(false);
        btnEstudiante.setFocusable(false);
        btnEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEstudiante);

        btnAcercaDe1.setContentAreaFilled(false);
        btnAcercaDe1.setFocusable(false);
        btnAcercaDe1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcercaDe1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAcercaDe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDe1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAcercaDe1);

        btnEstudiante1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/registro-en-linea.png"))); // NOI18N
        btnEstudiante1.setContentAreaFilled(false);
        btnEstudiante1.setFocusable(false);
        btnEstudiante1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstudiante1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEstudiante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiante1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEstudiante1);

        btnAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_icon/busqueda.png"))); // NOI18N
        btnAcercaDe.setContentAreaFilled(false);
        btnAcercaDe.setFocusable(false);
        btnAcercaDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcercaDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAcercaDe);

        desktopPane.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 456, Short.MAX_VALUE))
        );

        fileMenu2.setMnemonic('f');
        fileMenu2.setText("File");

        exitMenuItem2.setMnemonic('x');
        exitMenuItem2.setText("Exit");
        exitMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu2.add(exitMenuItem2);

        menuBar.add(fileMenu2);

        JMenuAcerca.setMnemonic('h');
        JMenuAcerca.setText("Acerca de");

        menuItemInformacion.setMnemonic('c');
        menuItemInformacion.setText("Informacion");
        menuItemInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInformacionActionPerformed(evt);
            }
        });
        JMenuAcerca.add(menuItemInformacion);

        menuBar.add(JMenuAcerca);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItem2ActionPerformed

    private void menuItemInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInformacionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Creadora : Juana Isabel");
    }//GEN-LAST:event_menuItemInformacionActionPerformed

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        // TODO add your handling code here:
        InternalFromEstud est = new InternalFromEstud();
        desktopPane.add(est);
        est.show();
    }//GEN-LAST:event_btnEstudianteActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        // TODO add your handling code here:
        InternalInformacion Inf = new InternalInformacion();
        desktopPane.add(Inf);
        Inf.show();

    }//GEN-LAST:event_btnAcercaDeActionPerformed

    private void btnAcercaDe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDe1ActionPerformed
        // TODO add your handling code here:
        InternalInformacion Inf = new InternalInformacion();
        desktopPane.add(Inf);
        Inf.show();

    }//GEN-LAST:event_btnAcercaDe1ActionPerformed

    private void btnEstudiante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiante1ActionPerformed
        // TODO add your handling code here:
        InternalFromEstud est = new InternalFromEstud();
        desktopPane.add(est);
        est.show();
    }//GEN-LAST:event_btnEstudiante1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteMDIAplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteMDIAplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteMDIAplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteMDIAplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteMDIAplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuAcerca;
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnAcercaDe1;
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JButton btnEstudiante1;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem2;
    private javax.swing.JMenu fileMenu2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemInformacion;
    // End of variables declaration//GEN-END:variables

}
